language: node_js
node_js:
  - "12"
services:
  - docker
branches:
  only:
    - master

before_install:
  - npm install

script:
  - npm run build
  - git --version
  - git branch
  - git checkout master
  - git add .
  - git commit -m "我测试一下"
  - git branch
  - git push origin master
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t xintiaobrother-blogs .
  - docker images
  - docker tag xintiaobrother-blogs $DOCKER_USERNAME/xintiaobrother-blogs:latest
  - docker images
  - docker push $DOCKER_USERNAME/xintiaobrother-blogs:latest
