services:
  - docker

before_install:
  - npm install

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t xintiaobrother/xintiaobrother.github.io:latest .
  - docker push xintiaobrother/xintiaobrother.github.io:latest
