
language: node_js
node_js:
  - "8"
branches:
  only:
    - master
before_install:
  - npm install
services:
  - docker
script:
  - echo "$DOCKER_PASSWORD" | docker login docker.io -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t xintiaobrother-blogs .
  - docker images
  - docker tag xintiaobrother-blogs $DOCKER_USERNAME/xintiaobrother-blogs:latest
  - docker images
  - docker push $DOCKER_USERNAME/xintiaobrother-blogs:latest
